on:
    push:
      branches:
        - master
    pull_request:
      branches:
        - master
  
name: run tests
jobs:
    lint:  
        runs-on: ubuntu-latest
        steps:
          - name: Install Go
            uses: actions/setup-go@v2
            with:
                go-version: 1.14.x
          - name: Checkout code
            uses: actions/checkout@v2
          - name: Run linters
            uses: golangci/golangci-lint-action@v2
            with:
                version: v1.29
          - name: vet
            run: go vet .